/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddTextToPdfRouteImport } from './routes/add-text-to-pdf'
import { Route as AgeCalculatorRouteImport } from './routes/age-calculator'
import { Route as AnnotatePdfRouteImport } from './routes/annotate-pdf'
import { Route as ApplicationPdfOptimizerRouteImport } from './routes/application-pdf-optimizer'
import { Route as BasicCalculatorRouteImport } from './routes/basic-calculator'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as CompressPdfToTargetSizeRouteImport } from './routes/compress-pdf-to-target-size'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CropPdfRouteImport } from './routes/crop-pdf'
import { Route as DateCalculatorRouteImport } from './routes/date-calculator'
import { Route as DeletePdfPagesRouteImport } from './routes/delete-pdf-pages'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DocumentScannerRouteImport } from './routes/document-scanner'
import { Route as EditPdfRouteImport } from './routes/edit-pdf'
import { Route as ExtractPdfPagesRouteImport } from './routes/extract-pdf-pages'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FlattenPdfRouteImport } from './routes/flatten-pdf'
import { Route as GrayscalePdfRouteImport } from './routes/grayscale-pdf'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InterestCalculatorRouteImport } from './routes/interest-calculator'
import { Route as JpgToPdfRouteImport } from './routes/jpg-to-pdf'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as PassportPhotoRouteImport } from './routes/passport-photo'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as PasswordProtectPdfRouteImport } from './routes/password-protect-pdf'
import { Route as PdfHealthCheckerRouteImport } from './routes/pdf-health-checker'
import { Route as PdfMetadataCleanerRouteImport } from './routes/pdf-metadata-cleaner'
import { Route as PdfOcrRouteImport } from './routes/pdf-ocr'
import { Route as PdfPageNumberingRouteImport } from './routes/pdf-page-numbering'
import { Route as PdfPageSizeConverterRouteImport } from './routes/pdf-page-size-converter'
import { Route as PdfToJpgRouteImport } from './routes/pdf-to-jpg'
import { Route as PdfToPngRouteImport } from './routes/pdf-to-png'
import { Route as PdfToTextRouteImport } from './routes/pdf-to-text'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as PrintReadyPdfRouteImport } from './routes/print-ready-pdf'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as RandomPasswordGeneratorRouteImport } from './routes/random-password-generator'
import { Route as ReorderPdfPagesRouteImport } from './routes/reorder-pdf-pages'
import { Route as RotatePdfRouteImport } from './routes/rotate-pdf'
import { Route as SignPdfRouteImport } from './routes/sign-pdf'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SmartPdfAnalyzerRouteImport } from './routes/smart-pdf-analyzer'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestRunnerRouteImport } from './routes/test-runner'
import { Route as TimezoneConverterRouteImport } from './routes/timezone-converter'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UnitConverterRouteImport } from './routes/unit-converter'
import { Route as WatermarkPdfRouteImport } from './routes/watermark-pdf'
import { Route as WordCounterRouteImport } from './routes/word-counter'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTextToPdfRoute = AddTextToPdfRouteImport.update({
  id: '/add-text-to-pdf',
  path: '/add-text-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeCalculatorRoute = AgeCalculatorRouteImport.update({
  id: '/age-calculator',
  path: '/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotatePdfRoute = AnnotatePdfRouteImport.update({
  id: '/annotate-pdf',
  path: '/annotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationPdfOptimizerRoute = ApplicationPdfOptimizerRouteImport.update({
  id: '/application-pdf-optimizer',
  path: '/application-pdf-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicCalculatorRoute = BasicCalculatorRouteImport.update({
  id: '/basic-calculator',
  path: '/basic-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfToTargetSizeRoute = CompressPdfToTargetSizeRouteImport.update({
  id: '/compress-pdf-to-target-size',
  path: '/compress-pdf-to-target-size',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CropPdfRoute = CropPdfRouteImport.update({
  id: '/crop-pdf',
  path: '/crop-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DateCalculatorRoute = DateCalculatorRouteImport.update({
  id: '/date-calculator',
  path: '/date-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletePdfPagesRoute = DeletePdfPagesRouteImport.update({
  id: '/delete-pdf-pages',
  path: '/delete-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentScannerRoute = DocumentScannerRouteImport.update({
  id: '/document-scanner',
  path: '/document-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPdfRoute = EditPdfRouteImport.update({
  id: '/edit-pdf',
  path: '/edit-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractPdfPagesRoute = ExtractPdfPagesRouteImport.update({
  id: '/extract-pdf-pages',
  path: '/extract-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FlattenPdfRoute = FlattenPdfRouteImport.update({
  id: '/flatten-pdf',
  path: '/flatten-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const GrayscalePdfRoute = GrayscalePdfRouteImport.update({
  id: '/grayscale-pdf',
  path: '/grayscale-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestCalculatorRoute = InterestCalculatorRouteImport.update({
  id: '/interest-calculator',
  path: '/interest-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPdfRoute = JpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportPhotoRoute = PassportPhotoRouteImport.update({
  id: '/passport-photo',
  path: '/passport-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordProtectPdfRoute = PasswordProtectPdfRouteImport.update({
  id: '/password-protect-pdf',
  path: '/password-protect-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfHealthCheckerRoute = PdfHealthCheckerRouteImport.update({
  id: '/pdf-health-checker',
  path: '/pdf-health-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfMetadataCleanerRoute = PdfMetadataCleanerRouteImport.update({
  id: '/pdf-metadata-cleaner',
  path: '/pdf-metadata-cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfOcrRoute = PdfOcrRouteImport.update({
  id: '/pdf-ocr',
  path: '/pdf-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfPageNumberingRoute = PdfPageNumberingRouteImport.update({
  id: '/pdf-page-numbering',
  path: '/pdf-page-numbering',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfPageSizeConverterRoute = PdfPageSizeConverterRouteImport.update({
  id: '/pdf-page-size-converter',
  path: '/pdf-page-size-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToJpgRoute = PdfToJpgRouteImport.update({
  id: '/pdf-to-jpg',
  path: '/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPngRoute = PdfToPngRouteImport.update({
  id: '/pdf-to-png',
  path: '/pdf-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToTextRoute = PdfToTextRouteImport.update({
  id: '/pdf-to-text',
  path: '/pdf-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReadyPdfRoute = PrintReadyPdfRouteImport.update({
  id: '/print-ready-pdf',
  path: '/print-ready-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomPasswordGeneratorRoute = RandomPasswordGeneratorRouteImport.update({
  id: '/random-password-generator',
  path: '/random-password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorderPdfPagesRoute = ReorderPdfPagesRouteImport.update({
  id: '/reorder-pdf-pages',
  path: '/reorder-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatePdfRoute = RotatePdfRouteImport.update({
  id: '/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SignPdfRoute = SignPdfRouteImport.update({
  id: '/sign-pdf',
  path: '/sign-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartPdfAnalyzerRoute = SmartPdfAnalyzerRouteImport.update({
  id: '/smart-pdf-analyzer',
  path: '/smart-pdf-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRunnerRoute = TestRunnerRouteImport.update({
  id: '/test-runner',
  path: '/test-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const TimezoneConverterRoute = TimezoneConverterRouteImport.update({
  id: '/timezone-converter',
  path: '/timezone-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkPdfRoute = WatermarkPdfRouteImport.update({
  id: '/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WordCounterRoute = WordCounterRouteImport.update({
  id: '/word-counter',
  path: '/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-text-to-pdf': typeof AddTextToPdfRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/annotate-pdf': typeof AnnotatePdfRoute
  '/application-pdf-optimizer': typeof ApplicationPdfOptimizerRoute
  '/basic-calculator': typeof BasicCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-pdf-to-target-size': typeof CompressPdfToTargetSizeRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crop-pdf': typeof CropPdfRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/edit-pdf': typeof EditPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/faq': typeof FaqRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interest-calculator': typeof InterestCalculatorRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/passport-photo': typeof PassportPhotoRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/password-protect-pdf': typeof PasswordProtectPdfRoute
  '/pdf-health-checker': typeof PdfHealthCheckerRoute
  '/pdf-metadata-cleaner': typeof PdfMetadataCleanerRoute
  '/pdf-ocr': typeof PdfOcrRoute
  '/pdf-page-numbering': typeof PdfPageNumberingRoute
  '/pdf-page-size-converter': typeof PdfPageSizeConverterRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/print-ready-pdf': typeof PrintReadyPdfRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/random-password-generator': typeof RandomPasswordGeneratorRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-pdf-analyzer': typeof SmartPdfAnalyzerRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/test-runner': typeof TestRunnerRoute
  '/timezone-converter': typeof TimezoneConverterRoute
  '/tools': typeof ToolsRoute
  '/unit-converter': typeof UnitConverterRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-counter': typeof WordCounterRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-text-to-pdf': typeof AddTextToPdfRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/annotate-pdf': typeof AnnotatePdfRoute
  '/application-pdf-optimizer': typeof ApplicationPdfOptimizerRoute
  '/basic-calculator': typeof BasicCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-pdf-to-target-size': typeof CompressPdfToTargetSizeRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crop-pdf': typeof CropPdfRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/edit-pdf': typeof EditPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/faq': typeof FaqRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interest-calculator': typeof InterestCalculatorRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/passport-photo': typeof PassportPhotoRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/password-protect-pdf': typeof PasswordProtectPdfRoute
  '/pdf-health-checker': typeof PdfHealthCheckerRoute
  '/pdf-metadata-cleaner': typeof PdfMetadataCleanerRoute
  '/pdf-ocr': typeof PdfOcrRoute
  '/pdf-page-numbering': typeof PdfPageNumberingRoute
  '/pdf-page-size-converter': typeof PdfPageSizeConverterRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/print-ready-pdf': typeof PrintReadyPdfRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/random-password-generator': typeof RandomPasswordGeneratorRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-pdf-analyzer': typeof SmartPdfAnalyzerRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/test-runner': typeof TestRunnerRoute
  '/timezone-converter': typeof TimezoneConverterRoute
  '/tools': typeof ToolsRoute
  '/unit-converter': typeof UnitConverterRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-counter': typeof WordCounterRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-text-to-pdf': typeof AddTextToPdfRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/annotate-pdf': typeof AnnotatePdfRoute
  '/application-pdf-optimizer': typeof ApplicationPdfOptimizerRoute
  '/basic-calculator': typeof BasicCalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-pdf-to-target-size': typeof CompressPdfToTargetSizeRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crop-pdf': typeof CropPdfRoute
  '/date-calculator': typeof DateCalculatorRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/edit-pdf': typeof EditPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/faq': typeof FaqRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interest-calculator': typeof InterestCalculatorRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/passport-photo': typeof PassportPhotoRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/password-protect-pdf': typeof PasswordProtectPdfRoute
  '/pdf-health-checker': typeof PdfHealthCheckerRoute
  '/pdf-metadata-cleaner': typeof PdfMetadataCleanerRoute
  '/pdf-ocr': typeof PdfOcrRoute
  '/pdf-page-numbering': typeof PdfPageNumberingRoute
  '/pdf-page-size-converter': typeof PdfPageSizeConverterRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/print-ready-pdf': typeof PrintReadyPdfRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/random-password-generator': typeof RandomPasswordGeneratorRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-pdf-analyzer': typeof SmartPdfAnalyzerRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/test-runner': typeof TestRunnerRoute
  '/timezone-converter': typeof TimezoneConverterRoute
  '/tools': typeof ToolsRoute
  '/unit-converter': typeof UnitConverterRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-counter': typeof WordCounterRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-text-to-pdf'
    | '/age-calculator'
    | '/annotate-pdf'
    | '/application-pdf-optimizer'
    | '/basic-calculator'
    | '/calculators'
    | '/compress-pdf'
    | '/compress-pdf-to-target-size'
    | '/contact'
    | '/cookie-policy'
    | '/crop-pdf'
    | '/date-calculator'
    | '/delete-pdf-pages'
    | '/disclaimer'
    | '/document-scanner'
    | '/edit-pdf'
    | '/extract-pdf-pages'
    | '/faq'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/how-it-works'
    | '/interest-calculator'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/passport-photo'
    | '/password-generator'
    | '/password-protect-pdf'
    | '/pdf-health-checker'
    | '/pdf-metadata-cleaner'
    | '/pdf-ocr'
    | '/pdf-page-numbering'
    | '/pdf-page-size-converter'
    | '/pdf-to-jpg'
    | '/pdf-to-png'
    | '/pdf-to-text'
    | '/pdf-to-word'
    | '/print-ready-pdf'
    | '/privacy-policy'
    | '/qr-code-generator'
    | '/qr-generator'
    | '/random-password-generator'
    | '/reorder-pdf-pages'
    | '/rotate-pdf'
    | '/sign-pdf'
    | '/sitemap.xml'
    | '/smart-pdf-analyzer'
    | '/split-pdf'
    | '/terms'
    | '/test-runner'
    | '/timezone-converter'
    | '/tools'
    | '/unit-converter'
    | '/watermark-pdf'
    | '/word-counter'
    | '/word-to-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-text-to-pdf'
    | '/age-calculator'
    | '/annotate-pdf'
    | '/application-pdf-optimizer'
    | '/basic-calculator'
    | '/calculators'
    | '/compress-pdf'
    | '/compress-pdf-to-target-size'
    | '/contact'
    | '/cookie-policy'
    | '/crop-pdf'
    | '/date-calculator'
    | '/delete-pdf-pages'
    | '/disclaimer'
    | '/document-scanner'
    | '/edit-pdf'
    | '/extract-pdf-pages'
    | '/faq'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/how-it-works'
    | '/interest-calculator'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/passport-photo'
    | '/password-generator'
    | '/password-protect-pdf'
    | '/pdf-health-checker'
    | '/pdf-metadata-cleaner'
    | '/pdf-ocr'
    | '/pdf-page-numbering'
    | '/pdf-page-size-converter'
    | '/pdf-to-jpg'
    | '/pdf-to-png'
    | '/pdf-to-text'
    | '/pdf-to-word'
    | '/print-ready-pdf'
    | '/privacy-policy'
    | '/qr-code-generator'
    | '/qr-generator'
    | '/random-password-generator'
    | '/reorder-pdf-pages'
    | '/rotate-pdf'
    | '/sign-pdf'
    | '/sitemap.xml'
    | '/smart-pdf-analyzer'
    | '/split-pdf'
    | '/terms'
    | '/test-runner'
    | '/timezone-converter'
    | '/tools'
    | '/unit-converter'
    | '/watermark-pdf'
    | '/word-counter'
    | '/word-to-pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-text-to-pdf'
    | '/age-calculator'
    | '/annotate-pdf'
    | '/application-pdf-optimizer'
    | '/basic-calculator'
    | '/calculators'
    | '/compress-pdf'
    | '/compress-pdf-to-target-size'
    | '/contact'
    | '/cookie-policy'
    | '/crop-pdf'
    | '/date-calculator'
    | '/delete-pdf-pages'
    | '/disclaimer'
    | '/document-scanner'
    | '/edit-pdf'
    | '/extract-pdf-pages'
    | '/faq'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/how-it-works'
    | '/interest-calculator'
    | '/jpg-to-pdf'
    | '/merge-pdf'
    | '/passport-photo'
    | '/password-generator'
    | '/password-protect-pdf'
    | '/pdf-health-checker'
    | '/pdf-metadata-cleaner'
    | '/pdf-ocr'
    | '/pdf-page-numbering'
    | '/pdf-page-size-converter'
    | '/pdf-to-jpg'
    | '/pdf-to-png'
    | '/pdf-to-text'
    | '/pdf-to-word'
    | '/print-ready-pdf'
    | '/privacy-policy'
    | '/qr-code-generator'
    | '/qr-generator'
    | '/random-password-generator'
    | '/reorder-pdf-pages'
    | '/rotate-pdf'
    | '/sign-pdf'
    | '/sitemap.xml'
    | '/smart-pdf-analyzer'
    | '/split-pdf'
    | '/terms'
    | '/test-runner'
    | '/timezone-converter'
    | '/tools'
    | '/unit-converter'
    | '/watermark-pdf'
    | '/word-counter'
    | '/word-to-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddTextToPdfRoute: typeof AddTextToPdfRoute
  AgeCalculatorRoute: typeof AgeCalculatorRoute
  AnnotatePdfRoute: typeof AnnotatePdfRoute
  ApplicationPdfOptimizerRoute: typeof ApplicationPdfOptimizerRoute
  BasicCalculatorRoute: typeof BasicCalculatorRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CompressPdfRoute: typeof CompressPdfRoute
  CompressPdfToTargetSizeRoute: typeof CompressPdfToTargetSizeRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CropPdfRoute: typeof CropPdfRoute
  DateCalculatorRoute: typeof DateCalculatorRoute
  DeletePdfPagesRoute: typeof DeletePdfPagesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DocumentScannerRoute: typeof DocumentScannerRoute
  EditPdfRoute: typeof EditPdfRoute
  ExtractPdfPagesRoute: typeof ExtractPdfPagesRoute
  FaqRoute: typeof FaqRoute
  FlattenPdfRoute: typeof FlattenPdfRoute
  GrayscalePdfRoute: typeof GrayscalePdfRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InterestCalculatorRoute: typeof InterestCalculatorRoute
  JpgToPdfRoute: typeof JpgToPdfRoute
  MergePdfRoute: typeof MergePdfRoute
  PassportPhotoRoute: typeof PassportPhotoRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PasswordProtectPdfRoute: typeof PasswordProtectPdfRoute
  PdfHealthCheckerRoute: typeof PdfHealthCheckerRoute
  PdfMetadataCleanerRoute: typeof PdfMetadataCleanerRoute
  PdfOcrRoute: typeof PdfOcrRoute
  PdfPageNumberingRoute: typeof PdfPageNumberingRoute
  PdfPageSizeConverterRoute: typeof PdfPageSizeConverterRoute
  PdfToJpgRoute: typeof PdfToJpgRoute
  PdfToPngRoute: typeof PdfToPngRoute
  PdfToTextRoute: typeof PdfToTextRoute
  PdfToWordRoute: typeof PdfToWordRoute
  PrintReadyPdfRoute: typeof PrintReadyPdfRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  RandomPasswordGeneratorRoute: typeof RandomPasswordGeneratorRoute
  ReorderPdfPagesRoute: typeof ReorderPdfPagesRoute
  RotatePdfRoute: typeof RotatePdfRoute
  SignPdfRoute: typeof SignPdfRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartPdfAnalyzerRoute: typeof SmartPdfAnalyzerRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TermsRoute: typeof TermsRoute
  TestRunnerRoute: typeof TestRunnerRoute
  TimezoneConverterRoute: typeof TimezoneConverterRoute
  ToolsRoute: typeof ToolsRoute
  UnitConverterRoute: typeof UnitConverterRoute
  WatermarkPdfRoute: typeof WatermarkPdfRoute
  WordCounterRoute: typeof WordCounterRoute
  WordToPdfRoute: typeof WordToPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-text-to-pdf': {
      id: '/add-text-to-pdf'
      path: '/add-text-to-pdf'
      fullPath: '/add-text-to-pdf'
      preLoaderRoute: typeof AddTextToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-calculator': {
      id: '/age-calculator'
      path: '/age-calculator'
      fullPath: '/age-calculator'
      preLoaderRoute: typeof AgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotate-pdf': {
      id: '/annotate-pdf'
      path: '/annotate-pdf'
      fullPath: '/annotate-pdf'
      preLoaderRoute: typeof AnnotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-pdf-optimizer': {
      id: '/application-pdf-optimizer'
      path: '/application-pdf-optimizer'
      fullPath: '/application-pdf-optimizer'
      preLoaderRoute: typeof ApplicationPdfOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-calculator': {
      id: '/basic-calculator'
      path: '/basic-calculator'
      fullPath: '/basic-calculator'
      preLoaderRoute: typeof BasicCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf-to-target-size': {
      id: '/compress-pdf-to-target-size'
      path: '/compress-pdf-to-target-size'
      fullPath: '/compress-pdf-to-target-size'
      preLoaderRoute: typeof CompressPdfToTargetSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-pdf': {
      id: '/crop-pdf'
      path: '/crop-pdf'
      fullPath: '/crop-pdf'
      preLoaderRoute: typeof CropPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-calculator': {
      id: '/date-calculator'
      path: '/date-calculator'
      fullPath: '/date-calculator'
      preLoaderRoute: typeof DateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-pdf-pages': {
      id: '/delete-pdf-pages'
      path: '/delete-pdf-pages'
      fullPath: '/delete-pdf-pages'
      preLoaderRoute: typeof DeletePdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-scanner': {
      id: '/document-scanner'
      path: '/document-scanner'
      fullPath: '/document-scanner'
      preLoaderRoute: typeof DocumentScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-pdf': {
      id: '/edit-pdf'
      path: '/edit-pdf'
      fullPath: '/edit-pdf'
      preLoaderRoute: typeof EditPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-pdf-pages': {
      id: '/extract-pdf-pages'
      path: '/extract-pdf-pages'
      fullPath: '/extract-pdf-pages'
      preLoaderRoute: typeof ExtractPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatten-pdf': {
      id: '/flatten-pdf'
      path: '/flatten-pdf'
      fullPath: '/flatten-pdf'
      preLoaderRoute: typeof FlattenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grayscale-pdf': {
      id: '/grayscale-pdf'
      path: '/grayscale-pdf'
      fullPath: '/grayscale-pdf'
      preLoaderRoute: typeof GrayscalePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interest-calculator': {
      id: '/interest-calculator'
      path: '/interest-calculator'
      fullPath: '/interest-calculator'
      preLoaderRoute: typeof InterestCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-pdf': {
      id: '/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/jpg-to-pdf'
      preLoaderRoute: typeof JpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-photo': {
      id: '/passport-photo'
      path: '/passport-photo'
      fullPath: '/passport-photo'
      preLoaderRoute: typeof PassportPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-protect-pdf': {
      id: '/password-protect-pdf'
      path: '/password-protect-pdf'
      fullPath: '/password-protect-pdf'
      preLoaderRoute: typeof PasswordProtectPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-health-checker': {
      id: '/pdf-health-checker'
      path: '/pdf-health-checker'
      fullPath: '/pdf-health-checker'
      preLoaderRoute: typeof PdfHealthCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-metadata-cleaner': {
      id: '/pdf-metadata-cleaner'
      path: '/pdf-metadata-cleaner'
      fullPath: '/pdf-metadata-cleaner'
      preLoaderRoute: typeof PdfMetadataCleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-ocr': {
      id: '/pdf-ocr'
      path: '/pdf-ocr'
      fullPath: '/pdf-ocr'
      preLoaderRoute: typeof PdfOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-page-numbering': {
      id: '/pdf-page-numbering'
      path: '/pdf-page-numbering'
      fullPath: '/pdf-page-numbering'
      preLoaderRoute: typeof PdfPageNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-page-size-converter': {
      id: '/pdf-page-size-converter'
      path: '/pdf-page-size-converter'
      fullPath: '/pdf-page-size-converter'
      preLoaderRoute: typeof PdfPageSizeConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-jpg': {
      id: '/pdf-to-jpg'
      path: '/pdf-to-jpg'
      fullPath: '/pdf-to-jpg'
      preLoaderRoute: typeof PdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-png': {
      id: '/pdf-to-png'
      path: '/pdf-to-png'
      fullPath: '/pdf-to-png'
      preLoaderRoute: typeof PdfToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-text': {
      id: '/pdf-to-text'
      path: '/pdf-to-text'
      fullPath: '/pdf-to-text'
      preLoaderRoute: typeof PdfToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-ready-pdf': {
      id: '/print-ready-pdf'
      path: '/print-ready-pdf'
      fullPath: '/print-ready-pdf'
      preLoaderRoute: typeof PrintReadyPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-password-generator': {
      id: '/random-password-generator'
      path: '/random-password-generator'
      fullPath: '/random-password-generator'
      preLoaderRoute: typeof RandomPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorder-pdf-pages': {
      id: '/reorder-pdf-pages'
      path: '/reorder-pdf-pages'
      fullPath: '/reorder-pdf-pages'
      preLoaderRoute: typeof ReorderPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-pdf': {
      id: '/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof RotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-pdf': {
      id: '/sign-pdf'
      path: '/sign-pdf'
      fullPath: '/sign-pdf'
      preLoaderRoute: typeof SignPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-pdf-analyzer': {
      id: '/smart-pdf-analyzer'
      path: '/smart-pdf-analyzer'
      fullPath: '/smart-pdf-analyzer'
      preLoaderRoute: typeof SmartPdfAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-runner': {
      id: '/test-runner'
      path: '/test-runner'
      fullPath: '/test-runner'
      preLoaderRoute: typeof TestRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timezone-converter': {
      id: '/timezone-converter'
      path: '/timezone-converter'
      fullPath: '/timezone-converter'
      preLoaderRoute: typeof TimezoneConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-converter': {
      id: '/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark-pdf': {
      id: '/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof WatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-counter': {
      id: '/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof WordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddTextToPdfRoute: AddTextToPdfRoute,
  AgeCalculatorRoute: AgeCalculatorRoute,
  AnnotatePdfRoute: AnnotatePdfRoute,
  ApplicationPdfOptimizerRoute: ApplicationPdfOptimizerRoute,
  BasicCalculatorRoute: BasicCalculatorRoute,
  CalculatorsRoute: CalculatorsRoute,
  CompressPdfRoute: CompressPdfRoute,
  CompressPdfToTargetSizeRoute: CompressPdfToTargetSizeRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CropPdfRoute: CropPdfRoute,
  DateCalculatorRoute: DateCalculatorRoute,
  DeletePdfPagesRoute: DeletePdfPagesRoute,
  DisclaimerRoute: DisclaimerRoute,
  DocumentScannerRoute: DocumentScannerRoute,
  EditPdfRoute: EditPdfRoute,
  ExtractPdfPagesRoute: ExtractPdfPagesRoute,
  FaqRoute: FaqRoute,
  FlattenPdfRoute: FlattenPdfRoute,
  GrayscalePdfRoute: GrayscalePdfRoute,
  HowItWorksRoute: HowItWorksRoute,
  InterestCalculatorRoute: InterestCalculatorRoute,
  JpgToPdfRoute: JpgToPdfRoute,
  MergePdfRoute: MergePdfRoute,
  PassportPhotoRoute: PassportPhotoRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PasswordProtectPdfRoute: PasswordProtectPdfRoute,
  PdfHealthCheckerRoute: PdfHealthCheckerRoute,
  PdfMetadataCleanerRoute: PdfMetadataCleanerRoute,
  PdfOcrRoute: PdfOcrRoute,
  PdfPageNumberingRoute: PdfPageNumberingRoute,
  PdfPageSizeConverterRoute: PdfPageSizeConverterRoute,
  PdfToJpgRoute: PdfToJpgRoute,
  PdfToPngRoute: PdfToPngRoute,
  PdfToTextRoute: PdfToTextRoute,
  PdfToWordRoute: PdfToWordRoute,
  PrintReadyPdfRoute: PrintReadyPdfRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  RandomPasswordGeneratorRoute: RandomPasswordGeneratorRoute,
  ReorderPdfPagesRoute: ReorderPdfPagesRoute,
  RotatePdfRoute: RotatePdfRoute,
  SignPdfRoute: SignPdfRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartPdfAnalyzerRoute: SmartPdfAnalyzerRoute,
  SplitPdfRoute: SplitPdfRoute,
  TermsRoute: TermsRoute,
  TestRunnerRoute: TestRunnerRoute,
  TimezoneConverterRoute: TimezoneConverterRoute,
  ToolsRoute: ToolsRoute,
  UnitConverterRoute: UnitConverterRoute,
  WatermarkPdfRoute: WatermarkPdfRoute,
  WordCounterRoute: WordCounterRoute,
  WordToPdfRoute: WordToPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
